setImageType('BRIGHTFIELD_H_DAB')
setColorDeconvolutionStains('{"Name" : "H&DAB default", "Stain 1" : "Hematoxylin", "Values 1" : "0.65 0.70 0.29", "Stain 2" : "DAB", "Values 2" : "0.27 0.57 0.78", "Background" : "255 255 255"}')
createSelectAllObject(true)
selectAnnotations()
runPlugin('qupath.imagej.detect.cells.PositiveCellDetection', '{"detectionImageBrightfield":"DAB OD","backgroundByReconstruction":true,"backgroundRadius":15.0,"medianRadius":0.0,"sigma":2.0,"minArea":10.0,"maxArea":1000.0,"threshold":0.005,"maxBackground":2.0,"watershedPostProcess":true,"cellExpansion":5.0,"includeNuclei":true,"smoothBoundaries":true,"makeMeasurements":true,"thresholdCompartment":"Nucleus: DAB OD mean","thresholdPositive1":0.2,"thresholdPositive2":0.4,"thresholdPositive3":0.6,"singleThreshold":true}')
